/* Parsegen autogenerated definition file - do not edit! */
/* clang-format off */

enum {
    predef_tt_error = 258,
    tt_end_of_file,
    tt_end_of_line,
    tt_bool_literal,
    tt_int_literal,
    tt_real_literal,
    tt_string_literal,
    tt_id,
    tt_ellipsis,
    tt_scope_resolution,
    tt_concatenate,
    tt_inc,
    tt_dec,
    tt_shl,
    tt_shr,
    tt_eq,
    tt_ne,
    tt_le,
    tt_ge,
    tt_and,
    tt_or,
    tt_add_assign,
    tt_sub_assign,
    tt_mul_assign,
    tt_div_assign,
    tt_mod_assign,
    tt_and_assign,
    tt_or_assign,
    tt_xor_assign,
    tt_shl_assign,
    tt_shr_assign,
    tt_arrow,
    tt_const,
    total_token_count
};

enum {
    predef_act_shift = 0,
    predef_act_reduce = 1,
    total_action_count
};

enum {
    sc_initial = 0
};
